### ISSUE TITLE
Addition to the game engine md file

### ISSUE THREAD

**Issue by Arnav0405** [Repositoir/doom-cpp#2]
Add as a new paragraph at the end 

So far layout! OpenGL as our GPU Graphics handling and everything related to game working. Instead of SFML I will be using SDL2 mostly for Window working and SDL will be working alongside openGL. Also yes, install GLAD in the same include directory as all other files. Current best tutorial for openGL with SDL2 for game engine dev: https://youtube.com/playlist?list=PLvv0ScY6vfd9zlZkIIqGDeG5TUWswkMox. Altho he only covers alot, for our specific need we will have to wing alot

**Comment by Repositoir** [comment]
Added
